name: Sync main with QA/UAT fixes
on:
  push:
    branches:
      - test
      - test-patch
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  sync-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Is PR required?
        id: pr_required
        run: echo "::set-output name=pr_required::$(git diff origin/main --quiet || echo 1)"
      - name: Extract branch name
        if: ${{ steps.pr_required.outputs.pr_required == 1}}
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: Ensure label is created
        shell: bash
        run: gh api repos/:owner/:repo/labels -f name="sync-pr" -f color="000000" || true
      - name: Create Pull Request
        if: ${{ steps.pr_required.outputs.pr_required == 1}}
        id: cpr
        run: >
          echo "::set-output name=pr_id::$(basename $(gh pr create --title 'Sync Fixes from ${{ steps.extract_branch.outputs.branch }} -  ${{ github.event.commits[0].message }}' --body '
            _This PR was auto-created due to PR on the ${{ steps.extract_branch.outputs.branch }} branch. It has been created to ensure any changes applied due to UAT testing or production issues are reconciled into the main integration branch ASAP_ 

            _Please review the following checklist to ensure that this PR is accepted and merged in the correct manner_

            - [ ] Changes approved by creator of the changes made on deploy/test
            - [ ] Approved by codeowners
            - [ ] _Merge pull request_ option to be used when merging this PR. **_Squash and merge_ should not be used!**
          ' --base main --head ${{ steps.extract_branch.outputs.branch }} --reviewer ${{github.event.pusher.name}} --label sync-pr))"
      - name: Echo Pull Request
        run: echo ${{ steps.cpr.outputs.pr_id }}
      - name: Is PR conflicted?
        if: ${{ steps.pr_required.outputs.pr_required == 1}}
        id: mergeable
        run: echo "::set-output name=state::$(gh api repos/:owner/:repo/pulls/${{ steps.cpr.outputs.pr_id  }} --jq '.mergeable_state')"
      - name: Close Pull Request
        if: ${{ steps.pr_required.outputs.pr_required == 1}} && ${{ steps.mergeable.outputs.state == 'dirty' }}
        run: gh pr close ${{ steps.cpr.outputs.pr_id }}
      - name: Comment Pull Request
        if: ${{ steps.pr_required.outputs.pr_required == 1}} && ${{ steps.mergeable.outputs.state == 'dirty'}}
        run: > 
          gh pr comment ${{ steps.cpr.outputs.pr_id }} -b '
            *Attention @${{github.event.pusher.name}}!* 
            _This PR has been caused due to conflicts. As we are unable to resolve conflicts directly on either main or ${{ steps.extract_branch.outputs.branch }}

            _Please follow the below steps to resolve:_
            ```
            git checkout main
            git pull
            git checkout -b conflicts/pr_${{ steps.cpr.outputs.pr_id }}
            git pull origin ${{ steps.cpr.outputs.pr_id }}
            # Resolve conflicts manually
            git commit
            git push
            ````

            _Then create a PR from conflicts/pr_${{ steps.cpr.outputs.pr_id }} to main_
          '

             
