name: Sync main with QA/UAT fixes
on:
  push:
    branches:
      - test
      - test-patch
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  sync-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: Create Pull Request
        id: cpr
        run: echo "::set-output name=pr_url::$(gh pr create --title 'Sync main with QA/UAT fixes' --body 'Sync fixes' --base main --head ${{ steps.extract_branch.outputs.branch }} )"
      - name: Print Pull Request
        run: echo '${{ steps.cpr.outputs.pr_url }}'
      - name: Auto Pull Request
        run: gh pr merge --auto --merge ${{ steps.cpr.outputs.pr_url }}
