name: Sync main with QA/UAT fixes
on:
  push:
    branches:
      - test
      - test-patch
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  sync-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: Create Pull Request
        if: ${{  steps.extract_branch.outputs.branch  != 'main' }}
        run: echo "::set-output name=pr_url::$(gh pr create --title 'Sync main with QA/UAT fixes ${GITHUB_RUN_ID}' --body 'Sync fixes ${GITHUB_RUN_ID}' --base main --head ${{ steps.extract_branch.outputs.branch }})"
      - name: Auto Pull Request
        if: ${{  steps.extract_branch.outputs.branch  != 'main' }}
        run: gh pr merge --auto --rebase ${{ steps.extract_branch.outputs.pr_url }}}
