name: Sync main with QA/UAT fixes
on:
  push:
    branches:
      - test
      - test-patch
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  sync-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Is PR required?
        id: pr_required
        run: echo "::set-output name=pr_required::$(git diff origin/main --quiet || echo 1)"
      - name: Extract branch name
        if: ${{ steps.pr_required.outputs.pr_required == 1}}
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: Echo Event pusher
        shell: bash
        run: echo ${{ github.event.pusher.name }}
      - name: Create Pull Request
        if: ${{ steps.pr_required.outputs.pr_required == 1}}
        id: cpr
        run: gh pr create --fill --base main --head ${{ steps.extract_branch.outputs.branch }}
